global:
  sendAnonymousUsage: false

log:
  level: DEBUG
accessLog: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  ssh-gitea:
    address: :22
  ssh-snips:
    address: :23

api:
  insecure: true
  dashboard: true

providers:
  docker:
    # endpoint: unix:///var/run/docker.sock
    # watch: true
    exposedByDefault: false
    network: traefik

certificatesResolvers:
  letsencrypt:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "spam@amyerskine.me"
      storage: "acme.json"

      httpChallenge:
        entryPoint: web
