services:
  traefik:
    image: traefik:v2.10.1
    container_name: traefik
    restart: unless-stopped
    command: "--providers.docker"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${SSH_PORT:-22}:22"
      - "127.0.0.1:8080:8080"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/traefik.yml:/traefik.yml:ro"
      - "./conf/acme.json:/acme.json"
networks:
  traefik:
    external: true
