services:
  web:
    image: nginx:1.17.6-alpine
    container_name: web
    volumes:
      - ./static:/usr/share/nginx/html
    labels:
      traefik.enable: true
      traefik.http.routers.web.tls: true
      traefik.http.routers.web.tls.certResolver: letsencrypt
      traefik.http.routers.web.tls.domains[0].main: amy.mov
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.rule: Host(`amy.mov`)
      traefik.http.services.web.loadbalancer.server.port: 80
    networks:
      - traefik
networks:
  traefik:
    external: true